# firstly we will claculate the how many monthly revnenue is generated by the company


import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_excel('cleaned.xlsx')
print(df)
print(df.columns)
monthly_revenue=df.groupby(df['Order_Date'].dt.month_name())['Revenue'].sum().reindex(['January','February','March','April','May','June','July','August','September','October','November','December'])
plt.plot(monthly_revenue.index,monthly_revenue.values,color='Red',marker='o',linestyle='--',label='Monthly Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.title('Monthly Revenue')
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig('MonthlyRevenue.png',dpi=300,bbox_inches='tight')
plt.show()


# now we will work on the profit generated in a month

# profit_month=df.groupby(df['Order_Date'].dt.month_name())['Profit'].sum().reindex(['January','February','March','April','May','June','July','August','September','October','November','December'])
# plt.plot(profit_month.index,profit_month.values,color='Blue',marker='o',label='2026 MICROSOFT PROFIT')
# plt.xlabel('Month')
# plt.ylabel('Profit')
# plt.title('Monthly Profit')
# plt.legend()
# plt.grid()
# plt.tight_layout()
# plt.savefig('Monthlyprofit.png',dpi=300,bbox_inches='tight')
# plt.show()